- name: Actions-runner docker-images
  community.docker.docker_container:
    name: actions-runner-docker-images
    state: present
    image: ghcr.io/actions/actions-runner:2.317.0
    command: ./config.sh --url https://github.com/chrlen/docker-images --token {{actions-runner-docker-images-token}}
