- name: Install required system packages
  ansible.builtin.apt:
    pkg: "{{ docker_packages }}"
    state: present
    update_cache: true
  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
  become: true

- name: Install Docker CE
  ansible.builtin.apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    update_cache: true
  become: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg: docker-compose
    state: present
    update_cache: true
  become: true

- name: Ensure docker deamon is running
  ansible.builtin.service:
    name: docker
    state: started
  become: true
